services:
  exposing:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./front-gfl/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ${CACHE_THUMBNAIL}:/var/www/thumbnails:ro
    depends_on:
      - frontend
  frontend:
    restart: always
    build:
      context: ./front-gfl
      dockerfile: dev.Dockerfile
      args:
        BUILD_ENV: development
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://frontend:5173" ]
      interval: 10s
      timeout: 5s
      retries: 3
    develop:
      watch:
        - action: sync
          path: ./front-gfl
          target: /app/
          ignore:
            - node_modules
        - action: rebuild
          path: vite.config.js
        - action: sync+restart
          path: .
          target: /app/other
          ignore:
            - thumbs
            - assets
            - front-gfl
  backend:
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
    build:
      context: .
      target: final
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      CACHE_THUMBNAIL: /var/www/thumbnails
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${CACHE_THUMBNAIL}:/var/www/thumbnails
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - front-gfl
            - target
            - thumbs
  redis:
    restart: always
    image: redis:8.0-M03-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5