services:
  exposing:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.base.conf:/etc/nginx/nginx.conf
      - thumbnails:/var/www/thumbnails:ro
      - tile_cache:/var/cache/nginx/qgis_tiles
      - ./maps:/var/www/frontend/public:ro
    depends_on:
      - frontend
  frontend:
    restart: always
    build:
      context: ./front-gfl
      dockerfile: dev.Dockerfile
      args:
        BUILD_ENV: development
        DISCORD_CLIENT_ID: ${DISCORD_AUTH2_CLIENT_ID}
        NEXT_PUBLIC_DISCORD_AUTH2_REDIRECT_URI: ${DISCORD_AUTH2_REDIRECT_URI}
        NEXTAUTH_URL: ${CLIENT_AUTH_REDIRECT_URI}
        DISCORD_CLIENT_SECRET: ${DISCORD_AUTH2_CLIENT_SECRET}
        STEAM_SECRET: ${STEAM_API_KEY}
        NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXT_PUBLIC_POSTHOG_KEY: ${NEXT_PUBLIC_POSTHOG_KEY}
        NEXT_PUBLIC_POSTHOG_HOST: ${NEXT_PUBLIC_POSTHOG_HOST}
        FRONTEND_URL: http://frontend:5173
        ANALYZE: ${ANALYZE}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://frontend:5173" ]
      interval: 10s
      timeout: 5s
      retries: 3
    develop:
      watch:
        - action: sync
          path: ./front-gfl
          target: /app/
          ignore:
            - node_modules
        - action: rebuild
          path: vite.config.js
        - action: sync+restart
          path: .
          target: /app/other
          ignore:
            - thumbs
            - assets
            - front-gfl
  backend:
    restart: always
    user: "10001:956"
    env_file:
      - .env
    build:
      context: .
      target: final
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CACHE_THUMBNAIL: /var/www/thumbnails
      STORE_UPLOAD: /var/www/maps
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - thumbnails:/var/www/thumbnails
      - ./maps:/var/www/maps:rw
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - front-gfl
            - target
            - thumbs
            - db.sql
  pfp-provider:
    build:
      context: ./pfp-provider
    environment:
      REDIS_URL: ${REDIS_URL}
      STEAM_API_KEY: ${STEAM_API_KEY}
  redis:
    restart: always
    image: redis:8.0-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
  qgis-server:
    volumes:
      - ./qgis-server/project:/home/qgis/project
    build:
      context: ./qgis-server
    environment:
      LANG: en_EN.UTF-8
      QGIS_PROJECT_FILE: /home/qgis/project/project.qgz
      QGIS_SERVER_LOG_LEVEL: 0
      DEBUG: 1
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: UTC


volumes:
  thumbnails:
  tile_cache: