FROM oven/bun:alpine AS builder

WORKDIR /app

COPY package*.json bun.lock ./

RUN bun ci

ARG BUILD_ENV=development
ARG DISCORD_CLIENT_ID=""
ARG NEXT_PUBLIC_DISCORD_REDIRECT_URI=""
ARG DISCORD_CLIENT_SECRET=""
ARG NEXT_PUBLIC_DOMAIN=""
ARG NEXTAUTH_SECRET=""
ARG STEAM_SECRET=""
ARG NEXTAUTH_URL=""

RUN printf "Building in environment: $BUILD_ENV\n"

COPY . .

RUN cat <<EOF > .env.development
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
NEXTAUTH_URL=${NEXTAUTH_URL}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
NEXT_PUBLIC_DISCORD_REDIRECT_URI=${NEXT_PUBLIC_DISCORD_REDIRECT_URI}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
STEAM_SECRET=${STEAM_SECRET}
NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
EOF

EXPOSE 5173

RUN apk add --no-cache curl

CMD ["bun", "run", "dev", "--", "-p", "5173"]